"""Tests for the P2-C1.4 X_W response validator and X_W construction.

Fixtures in fixtures/p2c14_xw are SYNTHETIC: packets generated by the real packet
generator from a 4-record toy cohort, and responses exported by the real annotator
(research/annotation_ui/P2_C1_4_XW_ANNOTATOR.html) driven in a headless browser.
"""
import json
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
FIX = Path(__file__).resolve().parent / "fixtures" / "p2c14_xw"
VAL = ROOT / "research/cohort/validate_P2_C1_4_XW_responses.py"
CON = ROOT / "research/cohort/construct_P2_C1_4_XW.py"
sys.path.insert(0, str(ROOT / "research/cohort"))
from construct_P2_C1_4_XW import rater_xw  # noqa: E402
from validate_P2_C1_4_XW_responses import validate  # noqa: E402


def load(name):
    return json.loads((FIX / name).read_text(encoding="utf-8"))


def write(tmp, name, obj):
    p = tmp / name
    p.write_text(json.dumps(obj), encoding="utf-8")
    return p


def test_fixture_responses_validate():
    for lab in "AB":
        v = validate(FIX / f"P2_C1_4_XW_RATER_{lab}.json", FIX / f"resp_{lab}.json")
        assert v["status"] == "PASS", v["problems"]


@pytest.mark.parametrize("mutate,needle", [
    (lambda r: r.update(packet_sha256="0" * 64), "packet_sha256"),
    (lambda r: r.update(rater_packet="B"), "rater_packet"),
    (lambda r: r.update(independence_attested=False), "attested"),
    (lambda r: r.update(complete=False), "complete"),
    (lambda r: r["cases"].pop(), "case IDs"),
    (lambda r: r["cases"].reverse(), "case IDs"),
    (lambda r: r["cases"][0].update(case_status="NO_USABLE_EVIDENCE"), "case_status"),
    (lambda r: r["cases"][0]["dimensions"]["W4"].update(witness="PRESENT"), "witness must be null"),
    (lambda r: r["cases"][0]["dimensions"]["W3"].update(notes=""), "UNCLEAR requires a reason"),
    (lambda r: r["cases"][0]["dimensions"]["W1"].update(applicable="MAYBE"), "invalid applicability"),
    (lambda r: r["cases"][0].update(y_h=0), "forbidden keys"),
])
def test_validator_rejects(tmp_path, mutate, needle):
    r = load("resp_A.json")
    mutate(r)
    v = validate(FIX / "P2_C1_4_XW_RATER_A.json", write(tmp_path, "r.json", r))
    assert v["status"] == "FAIL"
    assert any(needle in p for p in v["problems"]), v["problems"]


def test_nue_witness_must_be_null(tmp_path):
    r = load("resp_A.json")
    nue = next(c for c in r["cases"] if c["case_status"] == "NO_USABLE_EVIDENCE")
    nue["dimensions"]["W1"].update(applicable="YES", witness="PRESENT")
    v = validate(FIX / "P2_C1_4_XW_RATER_A.json", write(tmp_path, "r.json", r))
    assert v["status"] == "FAIL"


def case(status, **dims):
    d = {w: {"applicable": "NO", "witness": None, "notes": ""} for w in ("W1", "W2", "W3", "W4", "W5", "W6", "W7")}
    for w, (a, wit) in dims.items():
        d[w] = {"applicable": a, "witness": wit, "notes": "x"}
    return {"case_status": status, "dimensions": d}


def test_xw_rules():
    assert rater_xw(case("SUCCESS", W1=("YES", "PRESENT"), W2=("YES", "PRESENT")))[0] == 1.0
    assert rater_xw(case("SUCCESS", W1=("YES", "PRESENT"), W2=("YES", "ABSENT_OR_AMBIGUOUS")))[0] == 0.5
    # genuine UNCLEAR counts 0 and stays in the denominator, whatever witness was ticked
    assert rater_xw(case("SUCCESS", W1=("YES", "PRESENT"), W3=("UNCLEAR", "PRESENT")))[0] == 0.5
    # NO is excluded; empty denominator -> undefined
    assert rater_xw(case("SUCCESS"))[0] is None
    # NO_USABLE_EVIDENCE -> missing, never zero
    assert rater_xw(case("NO_USABLE_EVIDENCE", W1=("YES", None)))[0] is None


def run_construct(tmp, ra, rb):
    for f in ("P2_C1_4_XW_RATER_A.json", "P2_C1_4_XW_RATER_B.json", "P2_C1_4_XW_PACKET_MANIFEST.json"):
        shutil.copy(FIX / f, tmp / f)
    a, b = write(tmp, "ra.json", ra), write(tmp, "rb.json", rb)
    return subprocess.run([sys.executable, str(CON), "--packet-a", str(tmp / "P2_C1_4_XW_RATER_A.json"),
                           "--packet-b", str(tmp / "P2_C1_4_XW_RATER_B.json"),
                           "--packet-manifest", str(tmp / "P2_C1_4_XW_PACKET_MANIFEST.json"),
                           "--response-a", str(a), "--response-b", str(b), "--out", str(tmp / "out")],
                          capture_output=True, text=True)


def test_construct_end_to_end(tmp_path):
    p = run_construct(tmp_path, load("resp_A.json"), load("resp_B.json"))
    assert p.returncode == 0, p.stdout + p.stderr
    xw = json.loads((tmp_path / "out/P2_C1_4_XW.json").read_text())
    vals = {r["decision_id"]: r["x_w"] for r in xw["records"]}
    assert vals["T-000002"] is None and vals["T-000003"] is None  # NO_USABLE_EVIDENCE
    assert abs(vals["T-000001"] - 1 / 3) < 1e-12
    lock = json.loads((tmp_path / "out/P2_C1_4_XW_RAW_ANNOTATION_LOCK.json").read_text())
    assert lock["status"] == "RAW_ANNOTATIONS_LOCKED"


def test_construct_refuses_same_rater(tmp_path):
    rb = load("resp_B.json")
    rb["rater_id"] = load("resp_A.json")["rater_id"]
    assert run_construct(tmp_path, load("resp_A.json"), rb).returncode != 0


def test_construct_refuses_swapped_files(tmp_path):
    assert run_construct(tmp_path, load("resp_B.json"), load("resp_A.json")).returncode != 0


def test_construct_never_reads_cohort():
    src = CON.read_text(encoding="utf-8")
    assert "intervention_outcome" not in src and "aligned_records" not in src.lower().replace("never opens the aligned cohort", "")
